### ISSUE TITLE
搜索框左下角阴影问题

### ISSUE THREAD

**Issue by zhiiwg** [debiancn/autoindex-theme#3]
![image](https://cloud.githubusercontent.com/assets/4954007/25526800/df066684-2c47-11e7-9f41-596b91262d11.png)

如图，页面载入后搜索框左下角会有一块阴影，是该元素产生的：

![image](https://cloud.githubusercontent.com/assets/4954007/25526818/fc8f02e2-2c47-11e7-9ade-ba1f1e2af4f9.png)

**Comment by zhiiwg** [comment]
```css
.searchResult {
    display: none;  //解决页面搜索框初始阴影问题
    position: absolute;
    margin: 0;
    margin-top: 3px;
    padding: 0;
    background-color: #fff;
    border-bottom: 3px solid #D24C72;
    max-height: 10em;
    max-width: 30em;
    overflow-y: auto;
    overflow-x: hidden;
    font-size: 0.9em;
    box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2);
}
```
